web/printpenguin/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :sessions => "sessions" }
  resources :items do
    member do
      get 'cart'
      get 'download'
      get 'upload'
      get 'edit'
      get 'remove'
    end
  end

  root 'items#index'

end

web/printpenguin/app/models/item.rb
class Item < ActiveRecord::Base
end

web/printpenguin/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

web/printpenguin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

web/printpenguin/app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_filter :authenticate_user!
end

web/printpenguin/app/controllers/items_controller.rb
class ItemsController < BaseController
  def index
    if current_user != nil
      redirect_to cart_item_path(current_user)
    else
    end
  end

  def update
    if current_user != nil
      @item = Item.find(params[:id])
      if @item.update_attributes(item_params)
        redirect_to cart_item_path(current_user)
      else
        redirect_to cart_item_path(current_user), notice: "Something went wrong"
      end
    else
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to cart_item_path(current_user)
  end

  def cart
    user = User.find(params[:id])
    if user != nil
      @items = Item.where("user_id = ? AND is_ordered = ?", user.id, false)
    else
      redirect_to items_path, alert: "Please Log In"
    end
  end

  def create
    height = params['Height']
    width = params['Width']
    url = params['Url']
    email = params['User']
    mediatype = params['Mediatype']

    user = User.where(email: email).first

    item = Item.new(height: height, width: width, mediaurl: url, user_id: user.id, mediadatatype: mediatype, title: "11 x 17 Glossy Poster", description: "A medium sized poster perfect for any room")

    if item.save
      render js: "alert('success');"
    else
      render js: "alert('failure');"
    end
  end

  def item_params
    params.require(:item).permit(:title, :description, :height, :width, :mediaurl, :user_id, :mediadatatype, :quantity,
    :printype, :printwidth, :printheight, :frame_id, :album_id, :is_ordered, :is_shipped )
  end
end

web/printpenguin/app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  # POST /resource/sign_in
  def create
    super
    cookies[:username] = current_user.email
  end

  # GET /resource/sign_out
  def destroy
    super
  end
end

web/printpenguin/app/helpers/application_helper.rb
module ApplicationHelper
end

web/printpenguin/app/helpers/items_helper.rb
module ItemsHelper
end

web/printpenguin/app/views/items/cart.html.erb
<!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <%= link_to image_tag("logo3.png"), items_path, class:"navbar-brand" %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li>
                    <%= link_to "Download", items_path, class:"bigger" %>
                  </li>
                  <li>
                    <%= link_to "Upload", items_path, class:"bigger" %>
                  </li>
                  <li>
                    <div class="dropdown">
                      <a class="dropdown-toggle bigger" data-toggle="dropdown">Options<span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                        <li role="presentation", id:"options"><%= link_to 'Edit Profile',edit_user_registration_path, class:"options" %></li>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation", id:"options"><%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"options" %></li>
                      </ul>
                    </div>
                  </li>
                  <li>
                    <a href="<%= items_path %>" class="cart"><span class="fa-stack fa-2x">
                      <i class="fa fa-square-o fa-stack-2x"></i>
                      <i class="fa fa-shopping-cart fa-stack-1x"></i>
                    </span></a>
                  </li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      <!-- /.container -->
  </nav>

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-12">
        <h1>Items</h1>
        <div class="well well-sm">
          <% @items.each do |item| %>
            <div class="row nonstandard">
              <div class="col-md-6">
                <img src="<%= item.mediaurl %>" alt="<%= item.id %>" class="preview">
              </div>
              <div class="col-md-3">
                <h3><strong><%= item.title %></strong></h3>
                <h3><%= item.description %></h3></br>
                <% if item.album_id != nil %>
                  Album: <%= item.album_id %>
                <% elsif item.frame_id != nil %>
                  Frame: <%= item.frame_id %>
                <% end %>
              </div>
              <div class="col-md-3">
                <h4><a href="<%= edit_item_path(item) %>">edit</a></h4>
                <%= form_for item do |form| %>
                  <h4><%= form.label "Qty:" %>
                  <%= form.text_field :quantity, autocomplete: "off", class:"form-control" %></h4>
                  <%= form.submit "Update", class:"btn btn-warning btn-sm" %>
                <% end %>
                <h4><%= link_to "remove", item_path(item), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %></h4>
              </div>
            </div>
            <hr>
          <% end %>
          <% if @items.count < 5 %>
            <% extra = 5 - @items.count %>
            <% while extra > 0 do %>
              <div class="row standard">
              </div>
              <hr>
              <% extra = extra-1 %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-md-4 col-sm-12">
        <div class="well well-sm">
        </div>
      </div>
    </div>
  </div>

web/printpenguin/app/views/items/index.html.erb
  <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to image_tag("logo3.png"), items_path, class:"navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#sec1", class="fronter">Download</a>
                    </li>
                    <!--
                    <li>
                        <a href="#sec15">Latest Purchases</a>
                    </li>
                    -->
                    <li>
                        <a href="#sec2", class="fronter">Process</a>
                    </li>
                    <li>
                        <a href="#sec3", class="fronter">Options</a>
                    </li>
                    <li>
                        <a href="#sec4", class="fronter">Contact</a>
                    </li>
                    <li>
                        <%= button_to "Sign up", new_user_registration_path, class: 'btn btn-default moveit', method:"get" %>
                    </li>
                    <li>
                        <%= button_to "Log in", new_user_session_path, class: 'btn btn-warning moveitfarther', method:"get" %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <div id="sec1">
          <div class="row">
            <div class="col-md-3 col-sm-12">
              <div class='center'><%= link_to image_tag("Emperorpenguinfinalbigflip.png", class:'bigpenguin'), items_path %></div>
            </div>
            <div class="col-md-6 col-sm-12 hero-spacer">
              <h1>Get the Penguin!</h1>
              <div class="well well-sm">
                <h2>Download the Print Penguin Extension (only available to Chrome users)</h2>
                <p><%= button_to "Download", items_path , class: 'btn btn-warning btn-lg', method:"get" %></p>
              </div>
            </div>
            <div class="col-md-3 col-sm-12">
              <div class='center'><%= link_to image_tag("Emperorpenguinfinalbig.png", class:'bigpenguin'), items_path %></div>
            </div>
          </div>
        </div>

        <hr>
        <!--
        <div id="sec15">
          <div class="row">
              <div class="col-lg-12">
                  <h1>Latest Purchases</h1>
              </div>
          </div>

        </div>

        <hr>
        -->

        <div id="sec2">
          <!-- Title -->
          <div class="row">
              <div class="col-lg-12">
                  <h1>The Process</h1>
              </div>
          </div>
          <!-- /.row -->

          <!-- Page Features -->
          <div class="row text-center">
              <div class="col-md-1 col-sm-3"><i class="fa fa-arrow-right fa-5x"></i></div>
              <div class="col-md-3 col-sm-9 hero-feature">
                <%= image_tag("http://placehold.it/300x300", width:'100%') %>
                <div class="caption">
                    <h2>Select your Image</h2>
                </div>
              </div>

              <div class="col-md-1 col-sm-3"><i class="fa fa-arrow-right fa-5x"></i></div>
              <div class="col-md-3 col-sm-9 hero-feature">
                <%= image_tag("http://placehold.it/300x300", width:'100%') %>
                <div class="caption">
                    <h2>Edit and Design</h2>
                </div>
              </div>

              <div class="col-md-1 col-sm-3"><i class="fa fa-arrow-right fa-5x"></i></div>
              <div class="col-md-3 col-sm-9 hero-feature">
                <%= image_tag("http://placehold.it/300x300", width:'100%') %>
                <div class="caption">
                    <h2>Print and Pay</h2>
                </div>
              </div>

          </div>
          <!-- /.row -->
        </div>

        <hr>

        <div id="sec3">

          <div class="row">
              <div class="col-lg-12">
                  <h1>Options</h1>
              </div>
          </div>

          <div class="row text-center">

              <div class="col-md-3 col-sm-6 hero-feature">
                  <div class="thumbnail">
                      <img src="http://placehold.it/800x500" alt="">
                      <div class="caption">
                          <h3>Posters</h3>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                          <p>
                              <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                          </p>
                      </div>
                  </div>
              </div>

              <div class="col-md-3 col-sm-6 hero-feature">
                  <div class="thumbnail">
                      <img src="http://placehold.it/800x500" alt="">
                      <div class="caption">
                          <h3>Prints</h3>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                          <p>
                              <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                          </p>
                      </div>
                  </div>
              </div>

              <div class="col-md-3 col-sm-6 hero-feature">
                  <div class="thumbnail">
                      <img src="http://placehold.it/800x500" alt="">
                      <div class="caption">
                          <h3>Framed Prints</h3>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                          <p>
                              <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                          </p>
                      </div>
                  </div>
              </div>

              <div class="col-md-3 col-sm-6 hero-feature">
                  <div class="thumbnail">
                      <img src="http://placehold.it/800x500" alt="">
                      <div class="caption">
                          <h3>Penguin Books</h3>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                          <p>
                              <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                          </p>
                      </div>
                  </div>
              </div>

          </div>
        </div>

        <hr>

        <div id="sec4">
          <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
              <h2>Contact us with any questions or suggestions</h2>
              <h3>Email: andrew@print-penguin.com</h3>
              <h3>Address: 986 5th Ave. W., Suite C</h3>
              <h3>West Fargo ND, 58078</h3>
            </div>
          </div>
        </div>


        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12 text-center">
                  <ul class="list-inline">
                    <li><i class="icon-facebook icon-2x"></i></li>
                    <li><i class="icon-twitter icon-2x"></i></li>
                    <li><i class="icon-tumblr icon-2x"></i></li>
                    <li><i class="icon-pinterest icon-2x"></i></li>
                  </ul>
                  <p>Copyright &copy; Print-Penguin.com 2015</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

web/printpenguin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Printpenguin</title>

  <!-- Bootstrap Core CSS -->
  <link href='/assets/bootstrap.min.css' rel='stylesheet'>
  <link href="/assets/heroic-features.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- jQuery -->
  <script src="/assets/jquery.js"></script>
  <!-- Bootstrap Core JavaScript -->
  <script src='/assets/bootstrap.min.js'></script>
  <script src="/assets/scripts.js"></script>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <% if notice != nil %>
      <div class="alert alert-info">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <h3><%= notice %></h3>
      </div>
    <% elsif alert != nil %>
      <div class="alert alert-warning">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <h3><%= alert %></h3>
      </div>
    <% end %>

    <%= yield %>

</body>
</html>

web/printpenguin/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>